use std::collections::HashMap;
use std::path::Path;

use rquickjs::{Context, Module, Runtime};

use crate::js_runtime::{bridge, fetch, loader, shims, storage, transpile};
use crate::plugins::PluginStore;

// Built-in module sources embedded at compile time.
// Bundles are generated by frontend/scripts/build-luna-modules.mjs (run from build.rs).
const LUNA_CORE_JS: &str = include_str!("../../frontend/dist/luna-core.mjs");
const LUNA_LIB_JS: &str = include_str!("../../frontend/dist/luna-lib.mjs");
const OBY_JS: &str = include_str!("../../frontend/dist/oby.mjs");
const INRIXIA_HELPERS_JS: &str = include_str!("../../frontend/dist/inrixia-helpers.mjs");

// Stubs and shims (static files, not built by esbuild)
const REACT_STUB_JS: &str = include_str!("../../frontend/src/quickjs-stubs/react.mjs");
const REACT_DOM_CLIENT_STUB_JS: &str =
    include_str!("../../frontend/src/quickjs-stubs/react-dom-client.mjs");
const REACT_JSX_RUNTIME_STUB_JS: &str =
    include_str!("../../frontend/src/quickjs-stubs/react-jsx-runtime.mjs");
const IDB_KEYVAL_SHIM_JS: &str = include_str!("../../frontend/src/quickjs-stubs/idb-keyval.mjs");

/// Manages the QuickJS runtime for executing TidaLuna plugins.
///
/// Owns the JS Runtime + Context, the module loader, and tracks
/// loaded plugin state.
pub struct PluginRuntime {
    rt: Runtime,
    ctx: Context,
    /// Map of plugin URL → loaded state
    loaded_plugins: HashMap<String, LoadedPlugin>,
}

struct LoadedPlugin {
    url: String,
    name: String,
    /// Whether the module has an `onUnload` export
    has_on_unload: bool,
}

impl PluginRuntime {
    /// Create a new plugin runtime with all shims, storage, and built-in modules.
    ///
    /// `db_path` is the path to plugins.db — a second SQLite connection is opened
    /// for the JS runtime's __storage_* globals (avoids Mutex deadlock with main store).
    pub fn new(db_path: &Path) -> anyhow::Result<Self> {
        let (rt, ctx) = crate::js_runtime::init()
            .map_err(|e| anyhow::anyhow!("Failed to init JS runtime: {e}"))?;

        // Initialize storage (thread-local SQLite connection)
        storage::init_storage(db_path)?;

        // Install shims (console already done in init)
        ctx.with(|ctx| {
            shims::install_shims(&ctx)?;
            fetch::install_fetch(&ctx)?;
            storage::install_storage(&ctx)?;
            bridge::install_bridge(&ctx)?;
            Ok::<_, rquickjs::Error>(())
        })
        .map_err(|e| anyhow::anyhow!("Failed to install shims: {e}"))?;

        // Set up module loader with built-in modules pre-registered
        let resolver = loader::LunaResolver;
        let luna_loader = loader::LunaLoader::new()
            // Dependencies first (no imports of their own)
            .with_js_module("react", REACT_STUB_JS)
            .with_js_module("react-dom/client", REACT_DOM_CLIENT_STUB_JS)
            .with_js_module("react/jsx-runtime", REACT_JSX_RUNTIME_STUB_JS)
            .with_js_module("oby", OBY_JS)
            .with_js_module("@inrixia/helpers", INRIXIA_HELPERS_JS)
            .with_js_module("idb-keyval", IDB_KEYVAL_SHIM_JS)
            // Luna modules (depend on the above)
            .with_js_module("@luna/core", LUNA_CORE_JS)
            .with_js_module("@luna/lib", LUNA_LIB_JS);
        rt.set_loader(resolver, luna_loader);

        Ok(Self {
            rt,
            ctx,
            loaded_plugins: HashMap::new(),
        })
    }

    /// Register a built-in module (e.g., @luna/core, @luna/lib).
    /// Must be called before loading plugins that depend on it.
    ///
    /// Note: Because rquickjs takes ownership of the loader in set_loader(),
    /// we rebuild the loader each time.  For a small number of modules this
    /// is fine.
    pub fn register_module(&self, name: &str, source: &str) -> anyhow::Result<()> {
        // Transpile if TypeScript
        let js = if name.ends_with(".ts") || name.ends_with(".mts") {
            transpile::transpile_ts(source, &format!("{name}.ts"))?
        } else {
            source.to_string()
        };

        // We can't modify the loader after set_loader, so we declare the module
        // directly in the context
        self.ctx.with(|ctx| {
            Module::declare(ctx.clone(), name, js.as_str())
                .map_err(|e| anyhow::anyhow!("Failed to declare module '{name}': {e}"))?;
            Ok(())
        })
    }

    /// Load and execute a plugin by URL.
    /// Fetches the code from the PluginStore, transpiles if needed, and executes.
    pub fn load_plugin(&mut self, store: &PluginStore, url: &str) -> anyhow::Result<()> {
        let code = store
            .get_code(url)
            .ok_or_else(|| anyhow::anyhow!("No code found for plugin '{url}'"))?;

        // Transpile TS → JS if needed
        let js = if url.ends_with(".ts") || url.ends_with(".mts") {
            transpile::transpile_ts(&code, url)?
        } else {
            // Try transpiling — if it fails, use raw code (already JS)
            transpile::transpile_ts(&code, &format!("{url}.mjs")).unwrap_or(code)
        };

        // Execute the plugin module
        let has_on_unload = self.ctx.with(|ctx| -> anyhow::Result<bool> {
            let module = Module::declare(ctx.clone(), url, js.as_str())
                .map_err(|e| anyhow::anyhow!("Failed to declare plugin '{url}': {e}"))?;

            let (evaluated, _promise) = module
                .eval()
                .map_err(|e| anyhow::anyhow!("Failed to evaluate plugin '{url}': {e}"))?;

            // Check for onUnload export
            let has_unload: bool = evaluated
                .get::<_, rquickjs::Function>("onUnload")
                .is_ok();

            Ok(has_unload)
        })?;

        // Execute pending jobs OUTSIDE ctx.with() to avoid RefCell double-borrow
        while self.rt.is_job_pending() {
            if self.rt.execute_pending_job().is_err() {
                break;
            }
        }

        self.loaded_plugins.insert(
            url.to_string(),
            LoadedPlugin {
                url: url.to_string(),
                name: url.to_string(),
                has_on_unload,
            },
        );

        crate::vprintln!("[PLUGIN] Loaded: {url} (onUnload: {has_on_unload})");
        Ok(())
    }

    /// Unload a plugin — calls its `onUnload` export if present.
    pub fn unload_plugin(&mut self, url: &str) -> anyhow::Result<()> {
        let plugin = self.loaded_plugins.remove(url);
        if let Some(plugin) = &plugin {
            if plugin.has_on_unload {
                self.ctx.with(|ctx| {
                    // Try to call the onUnload function
                    let code = format!(
                        r#"
                        try {{
                            const mod = globalThis.__loaded_modules && globalThis.__loaded_modules["{}"];
                            if (mod && typeof mod.onUnload === "function") mod.onUnload();
                        }} catch(e) {{
                            console.error("onUnload error:", e);
                        }}
                        "#,
                        url.replace('"', r#"\""#)
                    );
                    let _ = ctx.eval::<(), _>(code.as_str());
                });
            }
            crate::vprintln!("[PLUGIN] Unloaded: {url}");
        }
        Ok(())
    }

    /// Drive timers — should be called periodically.
    pub fn tick(&self) {
        self.ctx.with(|ctx| {
            let _ = shims::drive_timers(&ctx);
        });

        // Also execute any pending JS jobs
        while self.rt.is_job_pending() {
            if self.rt.execute_pending_job().is_err() {
                break;
            }
        }
    }

    /// Load all enabled plugins from the store.
    pub fn load_all_enabled(&mut self, store: &PluginStore) -> Vec<String> {
        let plugins = store.list();
        let mut loaded = Vec::new();

        for plugin in &plugins {
            if plugin.enabled {
                match self.load_plugin(store, &plugin.url) {
                    Ok(()) => loaded.push(plugin.url.clone()),
                    Err(e) => eprintln!("[PLUGIN] Failed to load '{}': {e}", plugin.url),
                }
            }
        }

        loaded
    }

    /// Get list of currently loaded plugin URLs.
    pub fn loaded_plugins(&self) -> Vec<String> {
        self.loaded_plugins.keys().cloned().collect()
    }

    /// Execute arbitrary JS in the plugin context (for debugging).
    pub fn eval(&self, code: &str) -> anyhow::Result<String> {
        self.ctx.with(|ctx| {
            let result: String = ctx
                .eval(code)
                .map_err(|e| anyhow::anyhow!("Eval error: {e}"))?;
            Ok(result)
        })
    }

    /// Drain queued JS code from __cef_eval calls.
    /// Call this AFTER releasing the AppState Mutex, then pass each
    /// string to `eval_js()` to execute in CEF.
    pub fn drain_cef_js(&self) -> Vec<String> {
        bridge::drain_cef_js()
    }

    /// Dispatch a Redux action intercept into the rquickjs context.
    pub fn dispatch_redux_action(&self, action_type: &str, payload_json: &str) {
        self.ctx.with(|ctx| {
            if let Err(e) = bridge::dispatch_redux_action(&ctx, action_type, payload_json) {
                eprintln!("[BRIDGE] dispatch_redux_action error: {e}");
            }
        });
    }

    /// Dispatch a CEF event into the rquickjs context.
    pub fn dispatch_event(&self, event_type: &str, payload_json: &str) {
        self.ctx.with(|ctx| {
            if let Err(e) = bridge::dispatch_event(&ctx, event_type, payload_json) {
                eprintln!("[BRIDGE] dispatch_event error: {e}");
            }
        });
    }

    /// Update the cached Redux state in rquickjs.
    pub fn update_redux_state(&self, state_json: &str) {
        self.ctx.with(|ctx| {
            if let Err(e) = bridge::update_redux_state(&ctx, state_json) {
                eprintln!("[BRIDGE] update_redux_state error: {e}");
            }
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    /// Create a test PluginRuntime with a temporary database.
    fn test_runtime() -> (PluginRuntime, tempfile::TempDir) {
        let dir = tempdir().unwrap();
        let db_path = dir.path().join("plugins.db");
        // Create the DB with required tables
        let conn = rusqlite::Connection::open(&db_path).unwrap();
        conn.execute_batch(
            "CREATE TABLE IF NOT EXISTS plugin_storage (
                namespace TEXT NOT NULL,
                key       TEXT NOT NULL,
                value     TEXT NOT NULL,
                PRIMARY KEY (namespace, key)
            );",
        )
        .unwrap();
        drop(conn);
        let rt = PluginRuntime::new(&db_path).unwrap();
        (rt, dir)
    }

    #[test]
    fn test_create_plugin_runtime() {
        let (_runtime, _dir) = test_runtime();
    }

    #[test]
    fn test_register_and_import_module() {
        let (runtime, _dir) = test_runtime();

        runtime
            .register_module("test-mod", "export const version = '1.0.0';")
            .unwrap();

        let result = runtime.eval("typeof globalThis").unwrap();
        assert_eq!(result, "object");
    }

    #[test]
    fn test_tick_drives_timers() {
        let (runtime, _dir) = test_runtime();

        runtime.ctx.with(|ctx| {
            let _: () = ctx
                .eval(
                    r#"
                globalThis.__ticked = false;
                setTimeout(() => { globalThis.__ticked = true; }, 0);
            "#,
                )
                .unwrap();
        });

        runtime.tick();

        runtime.ctx.with(|ctx| {
            let ticked: bool = ctx.eval("globalThis.__ticked").unwrap();
            assert!(ticked);
        });
    }

    #[test]
    fn test_fetch_works_in_runtime() {
        let (runtime, _dir) = test_runtime();

        runtime.ctx.with(|ctx| {
            let has_fetch: bool = ctx.eval("typeof fetch === 'function'").unwrap();
            assert!(has_fetch);
        });
    }

    #[test]
    fn test_builtin_modules_registered() {
        let (runtime, _dir) = test_runtime();

        // Verify built-in modules are importable
        runtime.ctx.with(|ctx| {
            let has_window: bool = ctx.eval("typeof window !== 'undefined'").unwrap();
            assert!(has_window, "window shim should be available");

            let has_storage: bool =
                ctx.eval("typeof __storage_get === 'function'").unwrap();
            assert!(has_storage, "__storage_get should be available");
        });
    }

    #[test]
    fn test_import_luna_core() {
        let (runtime, _dir) = test_runtime();

        runtime.ctx.with(|ctx| {
            let module = Module::declare(
                ctx.clone(),
                "__test_core",
                r#"
                import { Tracer, LunaPlugin, ReactiveStore, unloadSet, buildActions, interceptors } from "@luna/core";

                globalThis.__core_exports = {
                    hasTracer: typeof Tracer === "function",
                    hasLunaPlugin: typeof LunaPlugin === "function",
                    hasReactiveStore: typeof ReactiveStore === "function",
                    hasUnloadSet: typeof unloadSet === "function",
                    hasBuildActions: typeof buildActions === "object",
                    hasInterceptors: typeof interceptors === "object",
                };
                "#,
            )
            .expect("Failed to declare test module");

            let _ = module.eval().expect("Failed to evaluate test module");
        });

        // Drive pending jobs outside ctx.with()
        while runtime.rt.is_job_pending() {
            if runtime.rt.execute_pending_job().is_err() {
                break;
            }
        }

        runtime.ctx.with(|ctx| {
            let exports: rquickjs::Object = ctx.eval("globalThis.__core_exports").unwrap();
            assert!(exports.get::<_, bool>("hasTracer").unwrap(), "Tracer should be a function");
            assert!(exports.get::<_, bool>("hasLunaPlugin").unwrap(), "LunaPlugin should be a function");
            assert!(exports.get::<_, bool>("hasReactiveStore").unwrap(), "ReactiveStore should be a function");
            assert!(exports.get::<_, bool>("hasUnloadSet").unwrap(), "unloadSet should be a function");
            assert!(exports.get::<_, bool>("hasBuildActions").unwrap(), "buildActions should be an object");
            assert!(exports.get::<_, bool>("hasInterceptors").unwrap(), "interceptors should be an object");
        });
    }

    #[test]
    fn test_import_luna_lib() {
        let (runtime, _dir) = test_runtime();

        // Use a wrapper module that catches import errors
        runtime.ctx.with(|ctx| {
            let module = Module::declare(
                ctx.clone(),
                "__test_lib",
                r#"
                import("@luna/lib")
                    .then(mod => {
                        globalThis.__lib_exports = {
                            hasRedux: typeof mod.redux === "object",
                            hasIpcRenderer: typeof mod.ipcRenderer === "object",
                            keys: Object.keys(mod).join(","),
                        };
                    })
                    .catch(e => {
                        globalThis.__lib_error = String(e) + "\n" + (e.stack || "no stack");
                    });
                "#,
            )
            .expect("Failed to declare test module");
            let _ = module.eval().expect("Failed to evaluate");
        });

        // Drive all pending jobs and promises
        for _ in 0..10 {
            while runtime.rt.is_job_pending() {
                let _ = runtime.rt.execute_pending_job();
            }
            runtime.tick();
        }

        runtime.ctx.with(|ctx| {
            // Check for error first
            let err: String = ctx.eval(r#"
                globalThis.__lib_error || ""
            "#).unwrap_or_default();
            if !err.is_empty() {
                panic!("@luna/lib import error: {err}");
            }

            let result: String = ctx.eval(r#"
                typeof globalThis.__lib_exports === "object"
                    ? JSON.stringify(globalThis.__lib_exports)
                    : "not set"
            "#).unwrap_or_else(|_| "eval failed".into());

            if result == "not set" {
                panic!("@luna/lib: exports not set (module never resolved)");
            }

            eprintln!("[TEST] luna-lib exports: {result}");
            let exports: rquickjs::Object = ctx.eval("globalThis.__lib_exports").unwrap();
            assert!(exports.get::<_, bool>("hasRedux").unwrap(), "redux should be an object");
            assert!(exports.get::<_, bool>("hasIpcRenderer").unwrap(), "ipcRenderer should be an object");
        });
    }

    #[test]
    fn test_import_helpers_and_oby() {
        let (runtime, _dir) = test_runtime();

        runtime.ctx.with(|ctx| {
            let module = Module::declare(
                ctx.clone(),
                "__test_deps",
                r#"
                import { Signal, memoize, Semaphore } from "@inrixia/helpers";
                import { store } from "oby";

                globalThis.__dep_exports = {
                    hasSignal: typeof Signal === "function",
                    hasMemoize: typeof memoize === "function",
                    hasSemaphore: typeof Semaphore === "function",
                    hasObyStore: typeof store === "function",
                };
                "#,
            )
            .expect("Failed to declare test module");

            let _ = module.eval().expect("Failed to evaluate test module");
        });

        while runtime.rt.is_job_pending() {
            if runtime.rt.execute_pending_job().is_err() {
                break;
            }
        }

        runtime.ctx.with(|ctx| {
            let exports: rquickjs::Object = ctx.eval("globalThis.__dep_exports").unwrap();
            assert!(exports.get::<_, bool>("hasSignal").unwrap(), "Signal should be a function");
            assert!(exports.get::<_, bool>("hasMemoize").unwrap(), "memoize should be a function");
            assert!(exports.get::<_, bool>("hasSemaphore").unwrap(), "Semaphore should be a function");
            assert!(exports.get::<_, bool>("hasObyStore").unwrap(), "oby store should be a function");
        });
    }

    #[test]
    fn test_idb_keyval_shim_roundtrip() {
        let (runtime, _dir) = test_runtime();

        runtime.ctx.with(|ctx| {
            let module = Module::declare(
                ctx.clone(),
                "__test_idb",
                r#"
                import { createStore, get, set, del, keys } from "idb-keyval";

                const store = createStore("test-plugin", "storage");

                // set → get roundtrip
                await set("mykey", { foo: "bar", num: 42 }, store);
                const val = await get("mykey", store);
                globalThis.__idb_value = JSON.stringify(val);

                // keys
                await set("other", "hello", store);
                const allKeys = await keys(store);
                globalThis.__idb_keys = JSON.stringify(allKeys);

                // del
                await del("mykey", store);
                const afterDel = await get("mykey", store);
                globalThis.__idb_deleted = afterDel === undefined;
                "#,
            )
            .expect("Failed to declare idb test module");

            let _ = module.eval().expect("Failed to evaluate idb test module");
        });

        while runtime.rt.is_job_pending() {
            if runtime.rt.execute_pending_job().is_err() {
                break;
            }
        }

        // Drive timers to resolve promises
        runtime.tick();

        runtime.ctx.with(|ctx| {
            let val: String = ctx.eval("globalThis.__idb_value").unwrap();
            assert_eq!(val, r#"{"foo":"bar","num":42}"#);

            let keys: String = ctx.eval("globalThis.__idb_keys").unwrap();
            let keys: Vec<String> = serde_json::from_str(&keys).unwrap();
            assert!(keys.contains(&"mykey".to_string()));
            assert!(keys.contains(&"other".to_string()));

            let deleted: bool = ctx.eval("globalThis.__idb_deleted").unwrap();
            assert!(deleted, "Value should be undefined after del");
        });
    }

    #[test]
    fn test_plugin_imports_luna_modules() {
        let (runtime, _dir) = test_runtime();

        // Simulate a plugin that imports from @luna/core and @luna/lib
        runtime.ctx.with(|ctx| {
            let module = Module::declare(
                ctx.clone(),
                "https://example.com/test-plugin",
                r#"
                Promise.all([
                    import("@luna/core"),
                    import("@luna/lib"),
                ]).then(([core, lib]) => {
                    globalThis.__plugin_loaded = true;
                    globalThis.__plugin_core_keys = Object.keys(core).join(",");
                    globalThis.__plugin_lib_keys = Object.keys(lib).join(",");
                }).catch(e => {
                    globalThis.__plugin_error = String(e) + "\n" + (e.stack || "");
                });
                "#,
            )
            .expect("Failed to declare plugin");

            let _ = module.eval().expect("Failed to evaluate plugin");
        });

        for _ in 0..10 {
            while runtime.rt.is_job_pending() {
                let _ = runtime.rt.execute_pending_job();
            }
            runtime.tick();
        }

        runtime.ctx.with(|ctx| {
            let err: String = ctx
                .eval(r#"globalThis.__plugin_error || """#)
                .unwrap_or_default();
            if !err.is_empty() {
                panic!("Plugin import error: {err}");
            }

            let loaded: bool = ctx.eval("globalThis.__plugin_loaded === true").unwrap();
            assert!(loaded, "Plugin should have loaded successfully");

            let core_keys: String = ctx.eval("globalThis.__plugin_core_keys").unwrap();
            assert!(core_keys.contains("Tracer"), "core should export Tracer");
            assert!(core_keys.contains("LunaPlugin"), "core should export LunaPlugin");

            let lib_keys: String = ctx.eval("globalThis.__plugin_lib_keys").unwrap();
            assert!(lib_keys.contains("redux"), "lib should export redux");
            assert!(lib_keys.contains("PlayState"), "lib should export PlayState");
        });
    }
}
