use super::transpile;
use super::wrapper;

/// Runtime state of a plugin in the CEF renderer.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PluginState {
    /// Code dispatched to renderer, awaiting `plugin_ready` ack.
    /// Fields: (load_id, nonce)
    Loading(u64, u64),
    /// Ack received - plugin fully initialized.
    /// Fields: (load_id, nonce)
    Ready(u64, u64),
}

/// Random `u64` nonce for the plugin-load ack handshake, or `None` if the
/// system RNG is unavailable. Generated off the AppState lock by the caller.
pub(crate) fn random_nonce() -> Option<u64> {
    random_nonce_with(|buf| match getrandom::fill(buf) {
        Ok(()) => true,
        Err(e) => {
            crate::vprintln!("[plugins] nonce entropy failure: {e}");
            false
        }
    })
}

/// `fill` returns true on success; entropy source is injected for testing.
fn random_nonce_with(fill: impl FnOnce(&mut [u8]) -> bool) -> Option<u64> {
    let mut buf = [0u8; 8];
    if !fill(&mut buf) {
        return None;
    }
    Some(u64::from_le_bytes(buf))
}

/// Manages plugin lifecycle: transpile, wrap, prepare for CEF injection.
///
/// The PluginManager does NOT inject code into CEF directly - it returns
/// JS strings that the caller passes to `eval_js()`.
///
/// Flow:
///   1. Plugin .mjs loaded from DB (PluginStore)
///   2. Transpiled TS→JS if needed (OXC)
///   3. Wrapped in security closure (wrapper.rs)
///   4. Returned as a JS string for injection into CEF
#[derive(Default)]
pub struct PluginManager {
    states: std::collections::HashMap<String, PluginState>,
    /// Reverse mapping: plugin manifest name → plugin URL.
    /// Used to validate `registerNative` callers.
    name_to_url: std::collections::HashMap<String, String>,
    next_load_id: u64,
}

impl PluginManager {
    pub fn new() -> Self {
        Self::default()
    }

    /// Transpile and wrap plugin code for CEF injection.
    /// The `load_id` is injected into the wrapper for ack correlation.
    pub fn transpile_and_wrap(
        plugin_id: &str,
        code: &str,
        load_id: u64,
        nonce: u64,
    ) -> anyhow::Result<String> {
        let js = transpile::transpile_ts(code, &format!("{plugin_id}.mts"))?;
        Ok(wrapper::wrap_plugin_code(plugin_id, &js, load_id, nonce))
    }

    /// Mark a plugin as Loading (code dispatched, awaiting ack).
    /// `name` is the manifest name (e.g. "DiscordRPC") - stored in the reverse
    /// mapping so `registerNative` can validate the caller. The `nonce` is
    /// generated by the caller off the AppState lock and injected into the
    /// wrapper alongside the returned `load_id` for ack correlation.
    pub fn mark_loading(&mut self, plugin_id: &str, name: &str, nonce: u64) -> u64 {
        let load_id = self.next_load_id;
        self.next_load_id += 1;
        self.states
            .insert(plugin_id.to_string(), PluginState::Loading(load_id, nonce));
        self.name_to_url
            .insert(name.to_string(), plugin_id.to_string());
        load_id
    }

    /// Look up the URL for a plugin by manifest name.
    pub fn url_for_name(&self, name: &str) -> Option<&str> {
        self.name_to_url.get(name).map(|s| s.as_str())
    }

    /// Transition Loading → Ready if load_id AND nonce match. Returns true if accepted.
    pub fn mark_ready(&mut self, plugin_id: &str, load_id: u64, nonce: u64) -> bool {
        match self.states.get(plugin_id) {
            Some(PluginState::Loading(cid, cn)) if *cid == load_id && *cn == nonce => {
                self.states
                    .insert(plugin_id.to_string(), PluginState::Ready(load_id, nonce));
                true
            }
            _ => false,
        }
    }

    /// Generate the JS cleanup code for a plugin (static, no state mutation).
    pub fn generate_unload_js(plugin_id: &str) -> String {
        let escaped = wrapper::escape_js(plugin_id);
        format!(
            "if(window.__pluginUnloads&&window.__pluginUnloads['{escaped}']){{window.__pluginUnloads['{escaped}']()}}"
        )
    }

    /// Remove a plugin from the state map (call AFTER eval_js dispatch of cleanup).
    pub fn mark_unloaded(&mut self, plugin_id: &str) {
        self.states.remove(plugin_id);
        self.name_to_url.retain(|_, url| url != plugin_id);
    }

    /// All currently loaded plugin URLs.
    pub fn loaded_urls(&self) -> Vec<String> {
        self.states.keys().cloned().collect()
    }

    /// True if the plugin is Loading or Ready.
    pub fn is_loaded(&self, plugin_id: &str) -> bool {
        self.states.contains_key(plugin_id)
    }

    /// True only if the plugin has received its ready ack.
    pub fn is_ready(&self, plugin_id: &str) -> bool {
        matches!(self.states.get(plugin_id), Some(PluginState::Ready(..)))
    }

    /// Get the current load_id for a plugin, if any.
    pub fn current_load_id(&self, plugin_id: &str) -> Option<u64> {
        self.states.get(plugin_id).map(|s| match s {
            PluginState::Loading(id, _) | PluginState::Ready(id, _) => *id,
        })
    }
}

#[cfg(test)]
#[path = "../../tests/unit/plugins/manager.rs"]
mod tests;
